# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-18 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
