# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-19 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_participants_is_loggedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='searching_pair',
            field=models.BooleanField(default=False),
        ),
    ]
