# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-23 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_participants_searching_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='started_playing',
            field=models.BooleanField(default=False),
        ),
    ]
