# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-18 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondaryimages',
            old_name='image',
            new_name='secondary_image',
        ),
        migrations.RemoveField(
            model_name='secondaryimages',
            name='parent_image',
        ),
    ]
