# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-20 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20191020_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpair',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
