# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-23 19:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20191021_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedpair',
            name='start_game',
            field=models.BooleanField(default=False),
        ),
    ]
