# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-23 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_sharedpair_start_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedpair',
            name='start_game',
        ),
    ]
